### PR TITLE
new port: sysutils/sysadmin-script-collection

### PR DESCRIPTION
**Pull request by AnotherKamila**
@adam-dej ping.
Ask if you have questions.

---

This change is [Reviewable](https://reviewable.io/reviews/trojsten/freebsd-custom-ports/1)

### CODE REVIEW

**Comment by adam-dej** [comment]
Maybe we should put  a TODO somewhere so that we won't forget to change `GH_TAGNAME` to a future final tag?

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[sysutils/sysadmin-script-collection/Makefile, line 14 [r1]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDijll5KsehTkqcSFHa:-KDijll5KsehTkqcSFHb:1217932650) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/282aac089695eaeaae5b3292b0793245404edaa7/sysutils/sysadmin-script-collection/Makefile#L14)):_
python3 dependency is missing. And what do we need tarsnap for?

---

_[sysutils/sysadmin-script-collection/Makefile, line 26 [r1]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDikzWphvSCrW6PcQSh:-KDikzWphvSCrW6PcQSi:1061877124) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/282aac089695eaeaae5b3292b0793245404edaa7/sysutils/sysadmin-script-collection/Makefile#L26)):_
You forgot `repo-dirty-checker`, both bin file and the config file.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KDilbaFIso-zgbJu7lP:1417683962)_

**Comment by AnotherKamila** [comment]
What for? Commit is good enough IMO.

(If you want something like "install the newest version" semantics, this is bad practice, because then the same port may install different stuff depending on the state of the real world. You should bump the port version if you want it to install different stuff. So commit is not worse than tag.)

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[sysutils/sysadmin-script-collection/Makefile, line 26 [r1]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDikzWphvSCrW6PcQSh:-KDitqCgBLqjViYc1uyk:1472118648) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/282aac089695eaeaae5b3292b0793245404edaa7/sysutils/sysadmin-script-collection/Makefile#L26)):_
You did not tell me to include it. It does not look ready. Is it ready? Who reviewed it? Did I review it? :D

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KDitBvEI3zi-UGZf1FZ:-1807298245)_

**Comment by AnotherKamila** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[sysutils/sysadmin-script-collection/Makefile, line 14 [r1]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDijll5KsehTkqcSFHa:-KDiv5Vf_Le4LmjrWmed:1958548702) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/282aac089695eaeaae5b3292b0793245404edaa7/sysutils/sysadmin-script-collection/Makefile#L14)):_
I said I was asleep. Done, thanks.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1)_

**Comment by adam-dej** [comment]
No, I don't want 'install the newest version' semantics, I just think that installing a tag will make it easier for someone to look up installed version of the scripts on github.

Don't you want tags to signify releases of our scripts? Anyway, I don't care, if commit is good enough, let's go with commit.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[sysutils/sysadmin-script-collection/Makefile, line 26 [r1]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDikzWphvSCrW6PcQSh:-KDiuz40xzU5_9miLC7T:-496432881) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/282aac089695eaeaae5b3292b0793245404edaa7/sysutils/sysadmin-script-collection/Makefile#L26)):_
I thought that we've agreed to include the whole repo. Everything that is in `master` should be ready.  There was a pull request (#6) for it. But the script itself is older, and I believe that you've looked at it at some point.

To be sure, please check it, and if it looks good to you, include it.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KDiuTNMKmIlOGXfLTBj:912982710)_

**Comment by AnotherKamila** [comment]
OK, in this case tag (as opposed to "branch") is OK. Whatever you prefer.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KDixS1y8t3Myd-OdHz3:-1706419113)_

**Comment by lubo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[sysutils/sysadmin-script-collection/Makefile, line 26 [r1]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDikzWphvSCrW6PcQSh:-KDkBRgejrylnyfPI5Pw:-1512719282) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/282aac089695eaeaae5b3292b0793245404edaa7/sysutils/sysadmin-script-collection/Makefile#L26)):_
@AnotherKamila: You didn't review it, but feel free to do an additional review. `repo-dirty-checker` is mostly done, but email notifications are not implemented yet as I haven't been given implementation details.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1)_

**Comment by adam-dej** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[sysutils/sysadmin-script-collection/Makefile, line 11 [r2]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDmP5Q06Wmcn6ejK2K-:-KDmP5Q1uo0TiHBdGI84:670860685) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/0cf62ce17f73f9a6cac06d3782a8c4a7de882e8f/sysutils/sysadmin-script-collection/Makefile#L11)):_
This does not work for me, `===>  License not correctly defined: for unknown licenses, defining LICENSE_PERMS is mandatory (otherwise use a known LICENSE)`.
It works if written in capitals.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1)_

**Comment by adam-dej** [comment]
Port installed with this Makefile from somewhere else than `/usr/ports/sysutils/sysadmin-script-collection` will cause system upgrade (`portmaster -abd`) to fail. Is there a feasible default workaround? Automatically mark this port as ignored for updates?

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KDmZjAjKbc844j371ps:-616699140)_

**Comment by AnotherKamila** [comment]
Hmm, ugly. You could for instance create the `/var/db/pkg/*/+IGNOREME` file for these -- see `portmaster(8)`.

BTW, not a problem with my port -- `portmaster` generally doesn't like custom ports, it would appear. It is possible that `portupgrade` is less custom-port-unfriendly, but I prefer to use `portmaster`.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[sysutils/sysadmin-script-collection/Makefile, line 11 [r2]](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-KDmP5Q06Wmcn6ejK2K-:-KDqzVVpfXmnpcHk5PX-:-2111230028) ([raw file](https://github.com/trojsten/freebsd-custom-ports/blob/0cf62ce17f73f9a6cac06d3782a8c4a7de882e8f/sysutils/sysadmin-script-collection/Makefile#L11)):_
Interesting, it worked for me... Anyway, fixed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KDqxePM9Rs4GzitA9FJ:1045874281)_

**Comment by adam-dej** [comment]
I've updated this for version 1.0. For config files I've also used `@sample` as recommended. Sorry, size is no longer `6666`. Please, look at my changes. Overall, it looks good and works.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KE3BYWmahDdpr_laTX0:-1629614296)_

**Comment by adam-dej** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1)_

**Comment by AnotherKamila** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/trojsten/freebsd-custom-ports/1#-:-KE3DIhr0MtZ1kVmXvw3:1417088721)_

**Pull request merged**
